import { AppProps } from 'next/app'
import { ChakraProvider, extendTheme } from '@chakra-ui/react'
import { BIZ_UDPGothic } from "next/font/google"

const font = BIZ_UDPGothic({ weight: ['400', '700'], subsets: ['japanese', 'latin'] })

/**
 * NOTE: theme generated by smart swatch
 * @see https://smart-swatch.netlify.app/#171923
 */
const dark = {
  50: '#f0f0fa',
  100: '#d1d3e1',
  200: '#b3b6c9',
  300: '#9499b4',
  400: '#777c9f',
  500: '#5d6385',
  600: '#484d69',
  700: '#34374b',
  800: '#1e212e',
  900: '#080b14',
}

export const theme = extendTheme({
  config: {
    initialColorMode: 'light',
    useSystemColorMode: true,
  },
  styles: {
    global: {
      body: {
        bg: 'dark.900',
        color: 'dark.100',
        letterSpacing: '.03em',
        fontFamily: font.style.fontFamily,
      },
    },
  },
  components: {
    Link: {
      baseStyle: {
        color: 'purple.200',
      },
    },
  },
  colors: {
    dark
  }
})

export default function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ChakraProvider theme={theme}>
      <Component {...pageProps} />
    </ChakraProvider>
  )
}
